### ISSUE TITLE
insertions stop happening altogether after you press and hold a key

### ISSUE THREAD

**Issue by bnt0** [co60ca/stella#11]
Happens after changes after version 96abb76.
Example: lolllllllllll (press and hold l, then release) lol (no more expansions, for any keys)

**Comment by co60ca** [comment]
Doesn't occur on master lolllllllllll wont type after lol because you didn't release, but typing lol after that should work. There is nothing counting keys any more just the last key event if it was released or pressed or "typed."

Are you sure you arn't out of date with master?

**Comment by bnt0** [comment]
You're right, pulled from master and it's not an issue any more. I'll mark it resolved.

**Comment by co60ca** [comment]
Glad, that would be a rabbit hole I would not like to go down
