### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by bnt0** [co60ca/stella#12]
I've been thinking of ways to start setting up automated tests. First it would be good to have some high level testing to catch bugs / breaking changes automatically. 

I'll try and set up something basic in the next few days, and get familiar with more of the code in the process.

**Comment by co60ca** [comment]
Luckily we already pull Xtst

**Comment by bnt0** [comment]
Could you please point me to the documentation for Xtst?

**Comment by co60ca** [comment]
https://www.x.org/releases/X11R7.7/doc/libXtst/xtestlib.html
https://www.x.org/releases/X11R7.7/doc/index.html

**Comment by co60ca** [comment]
You could also try using uiohook which may be more usable and portable (since this was intended to be cross plat at one point until I gave up on that)

**Comment by co60ca** [comment]
Thank you
