### ISSUE TITLE
Build protobuf source files in the build process

### ISSUE THREAD

**Issue by bnt0** [co60ca/stella#14]
I've been trying to build under Ubuntu, and it's problematic if the protobuf runtime is of a different version Both newer and older protobuf versions result in compilation failures and/or linking failures.

Luckily CMake has a module to help with this:
https://cmake.org/cmake/help/v3.0/module/FindProtobuf.html

**Comment by co60ca** [comment]
In the process of #20 
https://github.com/co60ca/stella/commit/7cc8cf347df8f853bc4b5a10c11f5542666ed17b
reopen if it is not satisifactory
