### ISSUE TITLE
Interactive config mode gets stuck in an infinite loop on Ctrl-D input

### ISSUE THREAD

**Issue by bnt0** [co60ca/stella#4]
Trying to exit interactive mode with `EOF` (Ctrl-D) results in the list of options being printed over and over.

```
$ stella-config -I
[> h) this text
a) add new shortcut
m) modify shortcut
r) remove shortcut
l) list all shortcuts
s) save settings
[> h) this text
a) add new shortcut
m) modify shortcut
r) remove shortcut
l) list all shortcuts
s) save settings
[> h) this text
a) add new shortcut
m) modify shortcut
r) remove shortcut
l) list all shortcuts
s) save settings
[> h) this text
a) add new shortcut
...
```

**Comment by co60ca** [comment]
The expected quit sequence is to CTRL+C, but it seems that EOF should be included as that appears to be how (at least) some applications exit. I just based it on my usual usage.

**Comment by bnt0** [comment]
Ctrl-C sends a SIGINT to the process, so it should be used when the user wants to immediately terminate the application. The process then exits with [error code 130](http://tldp.org/LDP/abs/html/exitcodes.html).

Conversely, with Ctrl-D we want the application to properly shut down, simple handling the end of standard input.

**Comment by bnt0** [comment]
It should be fixed with the pull request.
